### ISSUE TITLE
utf8mb4 issue

### ISSUE THREAD

**Issue by erinus** [Leantime/docker-leantime#1]
When I type utf-8 characters for my firstname and lastname in installation form, it can be accepted but shows '?' after logging in. And company name can show utf-8 characters.
![image](https://user-images.githubusercontent.com/4888506/70255271-765aa380-17c1-11ea-8789-ec7790c381ee.png)
I also change firstname and lastname in 'Edit Profile', but still show '?' character. Thanks for your nice work.

**Comment by marcelfolaron** [comment]
Hey, thank you for opening the issue. We are tracking UTF8 issue in https://github.com/Leantime/leantime/issues/71 
If you need an immediate solution there are a few sql scripts to alter the MySQL table to support UTF8. Otherwise I'll add an update script to the next release to update all tables.

**Comment by erinus** [comment]
Thnaks. Got it.
