### ISSUE TITLE
New Environment Variables in 2.1

### ISSUE THREAD

**Issue by marcelfolaron** [Leantime/docker-leantime#10]
- Add env set up to readme
- Ensure there are now conflicts with the current startup.sh and dockerfile

**Comment by lamping7** [comment]
* remove the `sed` in start
* call it entrypoint like everyone else?
* throw the session id into a env var instead of sed replace

Need a PR.? I can tackle while kids are napping.

Great project!

**Comment by marcelfolaron** [comment]
Thanks for the details. If you have time to do the PR that'd be awesome!

**Comment by lamping7** [comment]
i don't care about the name of start too much, but can do the rest tomorrow

**Comment by lamping7** [comment]
closed via #16
