### ISSUE TITLE
Tag releases to match the leantime version

### ISSUE THREAD

**Issue by lamping7** [Leantime/docker-leantime#11]
Can you guys version this with tags to match version of leantime? This would be great for updating and keeping track of which version you're on. I prefer not to use `latest`. It also allows you to keep improving here in this repo without screwing people up, rather than waiting for a versioning on the other end -- such as incorporating the new env configs. Also, you can have docker hub to auto build on pushed tags.

**Comment by marcelfolaron** [comment]
Yes, thanks for the ping! We'll make sure to release with tags moving
forward.
