### ISSUE TITLE
DB_PORT for Docker

### ISSUE THREAD

**Issue by A75G** [Leantime/docker-leantime#15]
Hello,
I have different port for MySQL tried adding DB_PORT MYSQL_PORT nothing works, im not sure if i missed env or its not there.

**Comment by marcelfolaron** [comment]
We just closed a similar issue on the main repo.
https://github.com/Leantime/leantime/issues/227

Are you running mysql 8? PHP below 7.2 required you to set the old
encryption for the password in mysql. I have a link on the other issue.

**Comment by A75G** [comment]
Im Running MariaDB 10.4

**Comment by tedstriker** [comment]
Despite that, having a separate environment variable for the database port would remove some guess-work, if it is possible to add the port to the host or if there are other ways to configure it.

**Comment by marcelfolaron** [comment]
You can add the port to the hostname using domain.com:PORT. 
I will add another env variable to allow setting the port separately

**Comment by GuilhermeDaniluski** [comment]
> You can add the port to the hostname using domain.com:PORT.

Unfortaly it did not work for me. Could you tell me the new env variable name?

**Comment by ronnyandre** [comment]
Any solution for this? Not sure why this ticket is closed if this doesn't work.

**Comment by marcelfolaron** [comment]
The ticket was closed by the OP. Seems the solution above (domain:port) worked for the user.
I'll reopen to investigate.
