### ISSUE TITLE
Container behind HTTPS proxy

### ISSUE THREAD

**Issue by StaryVena** [Leantime/docker-leantime#18]
I would like to use Leantime behind Traefik, html page is loaded (using Browser <-- HTTPS --> Proxy Traefik <--HTTP --> Leantime container ) but content like css, images are not. The problem is with absolute path to the content which  has defined HTTP protocol and it is blocked by browser:
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS.
Is it possible to use only relative paths or define somewhere protocol to use?

**Comment by slubb** [comment]
You can add to the environment with the web image in your docker-compose file.

LEAN_APP_URL={yourdomain} 

LEAN_APP_URL='https://leantime.thetraefikurl.com'

Worked for me.

**Comment by StaryVena** [comment]
It's working. Thank you very much.

**Comment by sailhobie** [comment]
In case anyone else finds this useful,
I was having the https behind Traefik issue and adding the APP_URL helped, however I was still getting errors when adding things like tasks and milestones. Eventually I figured out the errors were related to not having SMTP mail setup and it was trying send emails regarding the activity. Setting up mail/smtp in the config fixed the remaining errors.
