### ISSUE TITLE
Configurable SMTP settings?

### ISSUE THREAD

**Issue by damntourists** [Leantime/docker-leantime#28]
This isn't really an issue, more a question since I'm having trouble finding anything regarding email configuration. I'm curious if there's any way to configure email settings so I can ensure notifications are sent?

**Comment by damntourists** [comment]
I see now that I'm able to mount a path to /var/www/html/config/configuration.php with a custom config. Seems that this one https://github.com/Leantime/leantime/blob/master/config/configuration.sample.php is copied to that location automatically when the docker container starts up if not present which has SMTP settings.

**Comment by cstrat** [comment]
Is there a way to set this configuration in the docker-compose file?
Sounds like we would lose this configuration with each update if we need to manually set it?

**Comment by agent-squirrel** [comment]
> Is there a way to set this configuration in the docker-compose file? Sounds like we would lose this configuration with each update if we need to manually set it?

That config lives outside the container and you use Docker mounts to mount it to that location.

**Comment by cstrat** [comment]
Thanks @agent-squirrel - so you're saying you just create the file somewhere locally and mount that individual file from the container to point to the one outside of docker?

like so:

```docker
volumes:
      - "/home/server/configuration.php/:/var/www/html/config/configuration.php"
```

**Comment by agent-squirrel** [comment]
Yup that's it exactly.

Adam Heathcote - ***@***.*** - 0416363934

Join the Linux Foundation <https://www.linuxfoundation.org/> and support
Open Source software development
<https://www.linuxfoundation.org/>

**Comment by cstrat** [comment]
Ok done this, now, follow up, any ideas if there is a quick and easy way to check that the settings have loaded?

**Comment by agent-squirrel** [comment]
I usually just jump into the container and check the config inside.
`docker exec -it {container_name} /bin/bash`
To get inside the container then just cat the file out.

**Comment by cstrat** [comment]
Thanks, I honestly didnt even think to do that. All my config is there!
