### ISSUE TITLE
PHP 7.2 is EOL

### ISSUE THREAD

**Issue by sgissi** [Leantime/docker-leantime#32]
The docker image uses PHP 7.2 which is [EOL](https://www.php.net/eol.php). PHP 7.3 is [security only](https://www.php.net/supported-versions.php). Is there any reason it wouldn't work with PHP 7.4?

**Comment by marcelfolaron** [comment]
Thanks for pointing that out. We should update. I have been working on 7.4 locally and everything seems to be working

**Comment by PascalBru** [comment]
I tried to create a updated version of Dockerfile

@marcelfolaron Could you please check  if the [0001-use-php-7.4.patch.txt](https://github.com/Leantime/docker-leantime/files/5998273/0001-use-php-7.4.patch.txt) works.

**Comment by marcelfolaron** [comment]
Updated to PHP 8
