### ISSUE TITLE
Cannot update files using docker image

### ISSUE THREAD

**Issue by kevineaton** [Leantime/docker-leantime#4]
I have not tried installing from source, so I do not know if this is an issue with the source or the Docker image. However, when installing following the instructions, I cannot upload a new logo or user profile. I also could not find anyway to setup emails without connecting to the running instance and manually editing the configuration file.I run NGINX as a reverse proxy for SSL termination, hence the random port for the leantime container.

Version: 2.0.11

Script:

```
echo "Starting MySQL"

sudo docker run -d -p 3306:3306 --network leantime-net \
-e MYSQL_ROOT_PASSWORD=SNIP \
-e MYSQL_DATABASE=leantime \
-e MYSQL_USER=admin \
-e MYSQL_PASSWORD=SNIP \
-v /var/data:/var/lib/mysql \
--name mysql_leantime mysql:5.7 --character-set-server=utf8 --collation-server=utf8_unicode_ci

echo "Starting Leantime...."


sudo docker run -d -p 7803:80 --network leantime-net \
-e DB_HOST=mysql_leantime \
-e MYSQL_USER=admin \
-e MYSQL_PASSWORD=SNIP \
-e MYSQL_DATABASE=leantime \
--name leantime leantime/leantime:latest
```

**Comment by marcelfolaron** [comment]
Thanks for reaching out. Seems this is a permission problem. We'll take a look and send a fix

**Comment by jjensen90** [comment]
@kevineaton Could you please pull the latest image for `leantime/leantime:latest` (digest `sha256:3dc2ee8cfa862c80b32f588b346604a380854ae2e8ffe06bbfc8efb480332f97`) and try again, let me know if you still face the same issue.

**Comment by kevineaton** [comment]
Hello! I will take a peak when I get a chance to setup a new server. I went with the non-Docker version (which is running fine other than a weird S3 file upload issue I am investigating) since I didn't see a way to specify SMTP or S3 capabilities within the docker image without mounting a config file from the host or creating an image that inherits from the leantime image.

**Comment by kevineaton** [comment]
Hello, you can close this. It worked with the latest image. Thanks!
