### ISSUE TITLE
Edit User Issue

### ISSUE THREAD

**Issue by ParsecSolutions** [Leantime/docker-leantime#47]
Hi there

Am having issues with the edit user page. We set up using the docker image. I did find a solution for this when I tried searching for a fix. 

https://github.com/Leantime/leantime/pull/454

But then since we set up the tool using the docker image, finding it difficult to actually locate the individual file. How do I go about fixing this issue? I tried searching for it under /var/lib/docker/. But then guess that's not the right approach.

Any help would be highly appreciated.

Regards
Thomas

**Comment by marcelfolaron** [comment]
Hi,

Which version are you using? This was fixed in 2.1.9. Can you update to the
latest version?

**Comment by ParsecSolutions** [comment]
Thanks @marcelfolaron for the tip. We updated to v 2.1.9 and it's working fine now.

**Comment by ParsecSolutions** [comment]
@marcelfolaron A new issue seems to have popped up now. When I try editing values from rest of the modules I get the following error. Like editing a Milestone / To - Do
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/73608081/170503517-b4920141-dfa3-461f-b697-35166b91f7e4.png">

**Comment by marcelfolaron** [comment]
Fixed in 2.2
