### ISSUE TITLE
No easy way to run behind proxy with SSL

### ISSUE THREAD

**Issue by aiac** [Leantime/docker-leantime#8]
I tried to run leantime behind traefik proxy, but there is no way to change leantime URLs to use https instead of http. The frontend shown up, but completly unstyled due to mixed content restriction (many http request for scripts and stylesheets). What can I do to change them to https?

**Comment by marcelfolaron** [comment]
As of 2.0.14 you can update the $appURL in the configuration file. 
We'll have to make sure this can be set during start time via parameter.

**Comment by Nixellion** [comment]
Where's the configuration file in docker?

**Comment by marcelfolaron** [comment]
Within docker its in /var/www/html/config
If you are using environment variables you can set it via docker run 
```
docker run -d -p 80:80 --network {some optional network} \
-e LEAN_DB_HOST=mysql_leantime \
-e LEAN_DB_USER=admin \
-e LEAN_DB_PASSWORD=321.qwerty \
-e LEAN_DB_DATABASE=leantime \
-e LEAN_APPURL={yourdomain} \
--name leantime leantime/leantime:latest
```

**Comment by Nixellion** [comment]
Thank you. Well, editing files within docker is not a good idea, but can I mount that directory to host's dir?

**Comment by marcelfolaron** [comment]
Agreed, we need to update our Readme. As I mentioned you can use the environment variables to set the appURL. To mount the app directory you can use:

```
docker run -d -p 80:80 --network {some optional network} \
-e LEAN_DB_HOST=mysql_leantime \
-e LEAN_DB_USER=admin \
-e LEAN_DB_PASSWORD=321.qwerty \
-e LEAN_DB_DATABASE=leantime \
-e LEAN_APP_URL={your URL} \
-v {some dir with leantime checked out}:/var/www/html \
--name leantime leantime/leantime:latest
```

**Comment by marcelfolaron** [comment]
Closing this. Last discussion continued in #13

**Comment by lryjnks** [comment]
Pls add this to your Dockerhub Info :) thx!

**Comment by olenoerby** [comment]
I'd like to draw attention to how I fixed it here in https://github.com/Leantime/docker-leantime/issues/8:

Direct link to comment: 
https://github.com/Leantime/docker-leantime/issues/26#issuecomment-1043199892
