### ISSUE TITLE
[comment] Docker hub image on Raspberry Pi 4 

### ISSUE THREAD

**Issue by lamping7** [Leantime/docker-leantime#9]
This doesn't work out of the box on a Raspberry Pi 4. I'm going to note some things I did to get this to work for others that may run into problems. Now I can test it out with my team. Thanks for the project.

1. There isn't a mysql container for arm. So, I installed mariadb on the host OS (Raspbian Buster). Here is a decent guide: [here](https://pimylifeup.com/raspberry-pi-mysql/)
2. The entrypoint (start.sh) for the image on docker hub would crash. I had to clone the repo and build the image locally. I'm guessing things (the extensions) are not compiled for arm.
3.  Now you need to fuss with getting access to the database from inside the container. When a user for the database is created, don't use `@'localhost'`. Use `@'%'` or replace `%` with the subdomain/IP of your docker container. If you failed to do this, you'll need to fix it using the `GRANT` command. See: [here](https://mariadb.com/kb/en/configuring-mariadb-for-remote-client-access/).
4. Make sure the mariadb is configured to setup the TCP port, by commenting out the `bind-address` in the configs. `#bind-address=127.0.0.1`, For me this was found in the file `/etc/mysql/mariadb.conf.d/50-server.cnf`, then restart mariadb `sudo systemctl restart mariadb.service` if you had to change this.
5. Finally, we have a slightly modified run command. I added the `--add-host=docker:xxx.xxx.xxx.xxx` option and removed the `--network`, making the `-e DB_HOST=docker`. Basically I kept a default bridged network with the host, but this allows the container to resolve the IP of your host. There are probably many ways to resolve this problem.

**Comment by marcelfolaron** [comment]
Thank you for this write up! It's awesome you got it to work on the Raspberry Pi! We'll try to make some modifications to support it better.

**Comment by ssilverr** [comment]
@marcelfolaron Hi there! Was there any progress on this issue?

**Comment by dekiesel** [comment]
FYI: The image `beercan1989/arm-mysql:5.7` works well for me on my pi4.

**Comment by marcelfolaron** [comment]
Add it to the documentation. Thanks for the input.
